name: Build and Release
on:
    workflow_dispatch:

jobs:
    build-and-release:
        name: "Build and Release"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  cache: "yarn"
                  node-version: "lts/*"

            # Workaround for yarn install timeouts, especially on Windows
            - run: yarn config set network-timeout 300000

            - name: Read package.json
              id: read_package
              run: echo "::set-output name=version::$(node -p \"require('./package.json').version\")"

            - name: Install dependencies
              run: yarn install

            - name: Build
              run: yarn build

            - name: Create tag
              run: git tag ${{ steps.read_package.outputs.version }}
              if: steps.read_package.outputs.version != ''

            - name: Push tag
              run: git push origin ${{ steps.read_package.outputs.version }}
              if: steps.read_package.outputs.version != ''

            - name: Create release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.read_package.outputs.version }}
                  release_name: Release ${{ steps.read_package.outputs.version }}
                  draft: false
                  prerelease: false

            - name: Create tar.gz file
              run: tar -czvf element-${{ steps.read_package.outputs.version }}.tar.gz webapp

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: element-${{ steps.read_package.outputs.version }}.tar.gz
                  path: element-${{ steps.read_package.outputs.version }}.tar.gz
