name: Build and Release
on:
    push:
        tags:
            - "*"

env:
    VERSION: ${{ github.ref.replace('refs/tags/', '') }}

jobs:
    build-and-release:
        name: "Build and Release"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  cache: "yarn"
                  node-version: "lts/*"

            # Workaround for yarn install timeouts, especially on Windows
            - run: yarn config set network-timeout 300000

            - name: Install dependencies
              run: yarn install

            - name: Build
              run: yarn build

            - name: Create release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ env.VERSION }}
                  release_name: Release ${{ env.VERSION }}
                  draft: false
                  prerelease: false

            - name: Create tar.gz file
              run: tar -czvf element-${{ env.VERSION }}.tar.gz webapp

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: element-${{ env.VERSION }}.tar.gz
                  path: element-${{ env.VERSION }}.tar.gz
